#!/bin/zsh

FILENAME=".warprc"
FILE=$HOME/$FILENAME

# if not exists
if [[ ! -e $FILE ]]
then
    touch $FILE
    print "No config file found so one was created"
fi

typeset -A points

# read config
while read line
do
    #print "line: \t" $line

    arr=(${(s,:,)line})
    key=${arr[1]}
    val=${arr[2]}

    #print "arr: \t" $arr

    points[$key]=$val

    print $key ':' ${points[$key]}
done < $FILE

print

# parse opts
while getopts "a:d:l" opt
do
    case $opt in
        a)
            print "-a was triggered, Parameter: $OPTARG"
            ;;
        d)
            print "-d was triggered, Parameter: $OPTARG"
            ;;
        l)
            print "-l was triggered"
            ;;
        \?)
            print "Usage: $0 [-s] [-d seplist] file ..."
            #"Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            print "Option -$OPTARG requires an argument."
            exit 1
            ;;
    esac
done
