.TH wd "1" "August 2014" "wd 0.4" "wd Manual"
.
.SH NAME
wd \- Quickly warp to custom directories in zsh
.
.
.SH SYNOPSIS
.B
wd [\fICOMMAND\fP] [\fINAME\fP]
.
.
.SH DESCRIPTION
\fBwd\fP (warp directory) lets you quickly jump to custom directories in zsh, without using \fBcd\fP. Why? Because \fBcd\fP is slow for  paths that are visited frequently or has a long path.
.
.
.SH COMMANDS
.IP "add, -a, --add <name>"
Add a new warp point which will warp to the current working directory with \fIname\fR as identifier.
.
.IP "add! <name>"
Like \fBadd\fP, but will overwrite existing point with the same \fIname\fP.
.
.IP "rm, -r, --remove <name>"
Remove any warp point with \fIname\fP as identifier.
.
.IP "ls, -l"
List all registered warp points.
.
.IP "show"
Show which warp points are registered to the current working directory.
.
.IP "show <name>"
Show path to given warp point.
.
.IP "clean"
Remove warp points to non-existent directories.
.
.IP "clean"
Like \fBclean\fP, but will not prompt for confirmation (force).
.
.IP "help"
Show help message with usage and commands.
.
.IP "-v, --version"
Print the running version.
.
.IP "-c, --config"
Specifically set the config file (default `~/.warprc`), which is useful when testing.
.
.IP "-d, --debug"
Force `exit` with return code after running. This is not default, as it will *exit your terminal*, though required when testing/debugging.
.
.IP "-q, --quiet"
Silence all output.
.
.
.SH EXAMPLES
.
.IP "\fBwd add! foo\fP"
Add warp point named "foo" to current working directory, overwriting any existing points named "foo".
.
.IP "\fBwd rm foo\fP"
Remove any warp point named \fIfoo\fP.
.
.
.SH BUGS
Issue tracking on GitHub:
.nf
https://github.com/mfaerevaag/wd/issues
.
.
.SH AUTHORS
Created and maintained by Markus Færevaag and Simon Altschuler, with the help of various contributors:
.nf
https://github.com/mfaerevaag/wd/graphs/contributors.
.
.
.SH LICENSE
wd is licensed under the MIT license.
